image:
  file: .gitpod.Dockerfile

ports:
  # Laravel server
  - port: 8000
    onOpen: open-preview
  # MySQL server
  - port: 3306
    onOpen: open-preview



tasks:
  - name: Nextjs
    init: npm install
    command: cd ./nextjs-typescript && npm install && npm run dev
  - name: Express
    init : cd ./express && npm run dev && ls
  - name: Laravel
    init : cd ./laravel && ls