tasks:
  - name: Django
    command: cd django && sudo apt-get update && sudo apt-get install python3 && pip install -r requirements.txt
    # init: python manage.py runserver
    
    
  - name: Nextjs
    command: cd nextjs && npm i 
    # init: npm run dev
    
    
    
    
    
    
    
                                                                                                                                                                                                                    
