# Generated by Django 3.2.9 on 2021-12-19 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(blank=True, max_length=100, null=True)),
                ('url', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
