# Generated by Django 3.2.9 on 2021-12-19 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_upload'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Upload',
            new_name='Bleze',
        ),
    ]
