import Navbar1 from "./Navbar/navbar1";
import Footer1 from './Footer/footer1'
import Script from 'next/script'
import Head from 'next/head'
// import Document, { Html, Head, Main, NextScript } from 'next/document'







export default function Layout({ children }) {
  return (
    <>
        <Script
          type="module" src="https://rawcdn.githack.com/Harry1o1/Pro-Component/cfeba9789dbccad1191a0f97fd2a841e89abc501/nextjs/ux/globals.js"
          strategy="beforeInteractive"
        />
        <Script
          src="https://rawcdn.githack.com/Harry1o1/Pro-Component/cfeba9789dbccad1191a0f97fd2a841e89abc501/nextjs/ux/boostrap.js"
          strategy="beforeInteractive"
        />
        <Script
          type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"
          strategy="beforeInteractive"
        />
        <Script
          nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"
          strategy="beforeInteractive"
        />

        <Head>
            <title>Todo</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="stylesheet" href="https://rawcdn.githack.com/Harry1o1/Pro-Component/2f0e84cfb7bbdd2642eff10af62ef9221c76b134/nextjs/styles/boostrap.css" />
            
        </Head>
        
      <Navbar1 />
      <main>{children}</main>
      <Footer1 />
    </>
  )
}













